---
- name: "Install nginx and congigure"
  hosts: webservers
  gather_facts: yes
  vars_files:
    - ./vars/ip_var_zabbix_server.yml
    - ./vars/main.yml
  roles:
  - include_role:
    name: nginx
    tasks_from: main