---
- name: "Install postgresql and congigure"
  hosts: zabbix
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
  - include_role:
    name: postgresql
    tasks_from: main