#cloud-config
users:
  - name: adrin
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgAU4q7+jxaKcYVQhCmzcoJzYkDfiP3HcN++hILtH/Tv3GYDL8jjB2DnaVL77CNDFtXjw148ToLx2FNDXw+irea0F1omRXFjGSMlpBHJk0ivMLtDl5NevnA99l7jA39i4sXnqai6+lLZi+dG5wsPXtGCT5PSotG/hsQ7vxK39XSkSRlPB5PqAm5/thGT6KPBrRVMnw52fDpS4RsegB15hqP/EVQdUzkLWIza+nJ0kEFVJArSZVt+TqNavnqb3FGUeWFjf4IA798RETF0n8HL5g5I80OFcep16MTV76ZOoqqd1rixrnfry3bWNGF36DguoQvmSjAqHjA+dMsmQDAX4h adrin@terraform