#cloud-config
users:
  - name: adrin
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGaK2I6MIx3HRbWftHIIx03XlOM66826iBnuAYs2b56s adrin@terraform