---
# tasks file for elasticsearch
# sudo apt update && sudo apt upgrade -y
- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

#- name: Upgrade the OS (apt-get dist-upgrade)
#  become: true
#  ansible.builtin.apt:
#    upgrade: dist

# sudo apt install gnupg apt-transport-https
- name: Install gnupg apt-transport-https
  become: true
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
    state: present

# wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add

#- name: Создание пользователя zabbix
#  become: true
#  ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add

# echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list

- name: Добавление в source list mirror.yandex elasticsearch
  become: true
  ansible.builtin.shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list

# sudo apt update && sudo apt install elasticsearch
- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

#  Установка elasticsearch
- name: Install elasticsearch (state=present is optional)
  become: true
  ansible.builtin.apt:
    name:
      - elasticsearch
    state: present

#sudo nano /etc/elasticsearch/elasticsearch.yml

- name: xpack.security.enabled - false
  become: true
  ansible.builtin.shell: sed -i 's/xpack.security.enabled:\true/xpack.security.enabled:\false/g' /etc/elasticsearch/elasticsearch.yml
  tags: securityfalse

# sudo systemctl daemon-reload
- name: Just force systemd to reread configs (2.4 and above)
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

# sudo systemctl enable elasticsearch.service
# sudo systemctl start elasticsearch.service

#- name: Start and enable service elasticsearch
#  ansible.builtin.service:
#    name: elasticsearch
#    state: started
#    enabled: yes

# sudo nano /etc/elasticsearch/elasticsearch.yml
# cluster.name: shafikov-netology
# systemctl restart elasticsearch


# 5. Установка zabbix-agent

- name: Install the zabbix-release_6.4-1 from a repo.zabbix.com
  become: true
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: "Install zabbix-agent"
  become: true
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

# 6. Рестарт и enabled zabbix-agent

- name: Импорт ip zabbix сервера
  become: true
  ansible.builtin.shell: sed -i 's/Server=127.0.0.1/Server={{ ip_zabbix_server }}/g' /etc/zabbix/zabbix_agentd.conf

- name: "Restart zabbix-agent"
  become: true
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes