---

# sudo apt update

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

#- name: Upgrade the OS (apt-get dist-upgrade)
#  become: true
#  ansible.builtin.apt:
#    upgrade: dist

- name: Install the zabbix-release_6.4-1 from a repo.zabbix.com
  become: true
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install zabbiz server, frontend, agent (state=present is optional)
  become: true
  ansible.builtin.apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.1-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Создание пользователя zabbix
  become: true
  ansible.builtin.shell: su - postgres -c 'psql --command "CREATE USER "{{ db_user }}" WITH PASSWORD '\'"{{ db_password }}"\'';"'

- name: Создание базы данных zabbix (владелец zabbix)
  become: true
  ansible.builtin.shell: su - postgres -c 'psql --command "CREATE DATABASE "{{ db_name }}" OWNER "{{ db_user }}";"'

- name: Импорт начальной схемы базы данных
  become: true
  ansible.builtin.shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u "{{ db_user }}" psql "{{ db_name }}"

- name: Импорт пароля базы данных
  become: true
  ansible.builtin.shell: sed -i 's/# DBPassword=/DBPassword={{ db_password }}/g' /etc/zabbix/zabbix_server.conf

# 6. Рестарт и enabled zabbix-server zabbix-agent nginx php8.1-fpm

- name: "Restart"
  become: true
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: "Restart"
  become: true
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: "Restart"
  become: true
  service:
    name: apache2
    state: restarted
    enabled: yes

