---
# tasks file for nginx

# 1. Установить веб-сервер nginx на web_host_1 и web_host_2.
- name: Install nginx (state=present is optional)
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: present

# 2.

- name: "Add Index page"
  become: yes
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: root
    group: root
    mode: 0755

# 3. Рестарт и enabled

- name: "Restart nginx"
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

# 4. Проверка доступности порта 80

- name: "Wait for port 80 to become open on the host, don't start checking for 5 seconds"
  wait_for:
    port: 80
    delay: 5